version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    ignore:
      - dependency-name: "react-native"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "expo"
      - dependency-name: "react-native-reanimated"
      - dependency-name: "react-native-screens"
