// GENERATED by tools/brand/build-brand-assets.cjs (npm run brand:build). Do not edit by hand.
// Colours measured from the Lioris emblem (blue, orange and berry families, light to deep).
export const BRAND_PALETTE = [
  { id: 'sky', hex: '#01AFFC' },
  { id: 'azure', hex: '#016FF2' },
  { id: 'cobalt', hex: '#0136CA' },
  { id: 'orange', hex: '#FD5401' },
  { id: 'tangerine', hex: '#F97C30' },
  { id: 'salmon', hex: '#FD895B' },
  { id: 'crimson', hex: '#E61548' },
  { id: 'magenta', hex: '#BD025D' },
  { id: 'plum', hex: '#9D286C' },
] as const;

export type BrandColorId = 'sky' | 'azure' | 'cobalt' | 'orange' | 'tangerine' | 'salmon' | 'crimson' | 'magenta' | 'plum';
export type BrandToneId = BrandColorId | 'white';
