// GENERATED by tools/brand/build-brand-assets.cjs (npm run brand:build). Do not edit by hand.
import type { BrandToneId } from './brandPalette';

export const WORDMARK_ASSETS: Record<BrandToneId, number> = {
  sky: require('../../assets/images/lioris_wordmark_sky.png'),
  azure: require('../../assets/images/lioris_wordmark_azure.png'),
  cobalt: require('../../assets/images/lioris_wordmark_cobalt.png'),
  orange: require('../../assets/images/lioris_wordmark_orange.png'),
  tangerine: require('../../assets/images/lioris_wordmark_tangerine.png'),
  salmon: require('../../assets/images/lioris_wordmark_salmon.png'),
  crimson: require('../../assets/images/lioris_wordmark_crimson.png'),
  magenta: require('../../assets/images/lioris_wordmark_magenta.png'),
  plum: require('../../assets/images/lioris_wordmark_plum.png'),
  white: require('../../assets/images/lioris_wordmark_white.png'),
};
