/**
 * Interactive Campus Map & Hall Locator API
 * Geocoded landmarks, faculty halls, libraries, and hostels for major Nigerian universities.
 * Integrated with OpenStreetMap Overpass API for live campus amenities (ATMs, food, health, study areas).
 */

export interface CampusLandmark {
  id: string;
  name: string;
  shortCode?: string;
  campus: string;
  category:
    | 'Lecture Hall'
    | 'Library'
    | 'Administrative'
    | 'Hostel'
    | 'Medical'
    | 'Food & Social'
    | 'Sports'
    | 'ATM & Bank';
  latitude: number;
  longitude: number;
  description: string;
  walkingTip?: string;
  amenityType?: string;
  isOsmLive?: boolean;
  distanceMeters?: number;
}

export interface CampusCenter {
  code: string;
  name: string;
  latitude: number;
  longitude: number;
}

export const CAMPUS_CENTERS: Record<string, CampusCenter> = {
  UI: {
    code: 'UI',
    name: 'University of Ibadan',
    latitude: 7.4478,
    longitude: 3.8992,
  },
  UNILAG: {
    code: 'UNILAG',
    name: 'University of Lagos',
    latitude: 6.5168,
    longitude: 3.398,
  },
  OAU: {
    code: 'OAU',
    name: 'Obafemi Awolowo University',
    latitude: 7.5186,
    longitude: 4.5276,
  },
  UNN: {
    code: 'UNN',
    name: 'University of Nigeria, Nsukka',
    latitude: 6.8667,
    longitude: 7.4106,
  },
  CU: {
    code: 'CU',
    name: 'Covenant University',
    latitude: 6.6719,
    longitude: 3.161,
  },
  FUNAAB: {
    code: 'FUNAAB',
    name: 'Federal University of Agriculture, Abeokuta',
    latitude: 7.2246,
    longitude: 3.4439,
  },
  FUTA: {
    code: 'FUTA',
    name: 'Federal University of Technology, Akure',
    latitude: 7.3045,
    longitude: 5.1384,
  },
  ABU: {
    code: 'ABU',
    name: 'Ahmadu Bello University',
    latitude: 11.1558,
    longitude: 7.6497,
  },
};

export const CAMPUS_LANDMARKS: CampusLandmark[] = [
  // FEDERAL UNIVERSITY OF AGRICULTURE, ABEOKUTA (FUNAAB)
  {
    id: 'funaab-senate-building',
    name: "Senate Building & Vice-Chancellor's Secretariat",
    shortCode: 'SENATE',
    campus: 'FUNAAB',
    category: 'Administrative',
    latitude: 7.2255,
    longitude: 3.4435,
    description: "Central administrative headquarters housing the Vice-Chancellor's office, Directorate of Academic Affairs, Registry, and Bursary.",
    walkingTip: 'Central focal point overlooking Motion Ground and the main university dual carriage driveway.',
  },
  {
    id: 'funaab-nimbe-adedipe-lib',
    name: "'Nimbe Adedipe Memorial Central Library",
    shortCode: 'LIBRARY',
    campus: 'FUNAAB',
    category: 'Library',
    latitude: 7.2248,
    longitude: 3.4442,
    description: 'Ultra-modern university research library with multi-floor study reading halls, digital e-learning labs, and postgraduate research rooms.',
    walkingTip: 'Facing Motion Ground directly; 1-minute walk from the Senate building.',
  },
  {
    id: 'funaab-mylt',
    name: 'Prof. Mahmood Yakubu Lecture Theatre (MYLT)',
    shortCode: 'MYLT',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2262,
    longitude: 3.4428,
    description: 'Iconic 2,000-seat multi-tiered central lecture auditorium for major university-wide courses, examinations, and national symposiums.',
    walkingTip: 'Immediately behind the Senate building; primary venue for 100L and 200L foundational lectures.',
  },
  {
    id: 'funaab-jao-complex',
    name: 'Julius Amioba Okojie (JAO) Lecture Theatre Complex (JAO 1, 2, 3)',
    shortCode: 'JAO',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2270,
    longitude: 3.4432,
    description: 'High-capacity lecture theatre wing hosting large foundational lectures for sciences, agriculture, and general studies.',
    walkingTip: 'North of MYLT; follow the paved walkway leading from Motion Ground.',
  },
  {
    id: 'funaab-oyewole-lt',
    name: 'Prof. Olusola Oyewole 1,000-Seater Lecture Theatre',
    shortCode: 'OYEWOLE-LT',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2258,
    longitude: 3.4418,
    description: 'Modern 1,000-capacity auditorium for inter-college lectures, matriculation overflow, and faculty seminars.',
    walkingTip: 'West of the Senate building adjacent to the Ceremonial Building arena.',
  },
  {
    id: 'funaab-tony-anenih-lt',
    name: 'Chief Tony Anenih Lecture Theatre (ANE 1 & 2)',
    shortCode: 'ANENIH-LT',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2265,
    longitude: 3.4422,
    description: 'Dual lecture theatre complex accommodating 1,000 students for engineering, agronomy, and social science classes.',
    walkingTip: 'Situated between the Ceremonial Building and the College of Engineering.',
  },
  {
    id: 'funaab-coleng',
    name: 'Chief Olusegun Obasanjo Building - COLENG Complex',
    shortCode: 'COLENG',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2285,
    longitude: 3.4412,
    description: 'College of Engineering headquarters, CAD studios, Civil, Mechanical, Mechatronics, and Electrical Engineering amphitheaters.',
    walkingTip: 'North academic sector along the engineering ring road, past the ICT Centre.',
  },
  {
    id: 'funaab-colphys',
    name: 'COLPHYS (College of Physical Sciences) Complex',
    shortCode: 'COLPHYS',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2268,
    longitude: 3.4455,
    description: 'Computer Science software labs, Mathematics lecture rooms, Physics research chambers, Statistics, and Chemistry demonstration auditoriums.',
    walkingTip: 'East of Motion Ground; connected via the paved central walkway corridor.',
  },
  {
    id: 'funaab-colbios',
    name: 'COLBIOS (College of Biological Sciences) Complex',
    shortCode: 'COLBIOS',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2275,
    longitude: 3.4468,
    description: 'Microbiology laboratories, Biochemistry research halls, Botany herbarium, and Zoology dissection rooms.',
    walkingTip: 'Adjacent to COLPHYS along the northern science avenue.',
  },
  {
    id: 'funaab-colamrud',
    name: 'COLAMRUD Lecture Complex & Deanery',
    shortCode: 'COLAMRUD',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2238,
    longitude: 3.4425,
    description: 'College of Agricultural Management, Rural Development, and Agricultural Economics classrooms and seminars.',
    walkingTip: 'South of the Senate building, near the practical farming demonstration pavilions.',
  },
  {
    id: 'funaab-colfhec',
    name: 'COLFHEC (Food Science & Human Ecology) Complex',
    shortCode: 'COLFHEC',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2242,
    longitude: 3.4462,
    description: 'Food processing pilot plant, sensory evaluation labs, Nutrition & Dietetics studios, and Home Science demonstration kitchens.',
    walkingTip: 'Directly across from the central library gardens.',
  },
  {
    id: 'funaab-colplant',
    name: 'COLPLANT (College of Plant Science & Crop Production)',
    shortCode: 'COLPLANT',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2225,
    longitude: 3.4415,
    description: 'Crop Protection, Horticulture, Plant Breeding, Seed Technology, and Soil Science research laboratories.',
    walkingTip: 'Southwestern campus sector leading toward DUFARMS.',
  },
  {
    id: 'funaab-colanim',
    name: 'COLANIM (College of Animal Science & Livestock Production)',
    shortCode: 'COLANIM',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2220,
    longitude: 3.4410,
    description: 'Animal Nutrition, Animal Breeding & Genetics, Pasture Management, and Dairy Science lecture theatres.',
    walkingTip: 'Adjacent to COLPLANT along the agricultural science loop road.',
  },
  {
    id: 'funaab-colvet',
    name: 'COLVET (College of Veterinary Medicine) & Teaching Hospital',
    shortCode: 'COLVET',
    campus: 'FUNAAB',
    category: 'Lecture Hall',
    latitude: 7.2215,
    longitude: 3.4398,
    description: 'Veterinary medicine lecture theatres, animal surgery suites, pathology wards, and clinical diagnosis complexes.',
    walkingTip: 'West wing of campus near the Veterinary Teaching Hospital entrance.',
  },
  {
    id: 'funaab-ceremonial-building',
    name: 'Ceremonial Building & Convocation Arena',
    shortCode: 'CONVO',
    campus: 'FUNAAB',
    category: 'Administrative',
    latitude: 7.2250,
    longitude: 3.4420,
    description: 'Grand 3,500-seat amphitheatre for university convocations, matriculations, and international conferences.',
    walkingTip: 'West of the Senate building facing the ceremonial parade grounds.',
  },
  {
    id: 'funaab-ict-centre',
    name: 'INPIRPU / ICT Resource Centre & CBT Hall',
    shortCode: 'ICT-CBT',
    campus: 'FUNAAB',
    category: 'Administrative',
    latitude: 7.2260,
    longitude: 3.4445,
    description: 'Central university ICT infrastructure, student e-testing CBT centres, and high-speed campus broadband hub.',
    walkingTip: 'North of Motion Ground between the Senate building and COLENG avenue.',
  },
  {
    id: 'funaab-health-centre',
    name: 'FUNAAB University Health Centre',
    shortCode: 'HEALTH',
    campus: 'FUNAAB',
    category: 'Medical',
    latitude: 7.2232,
    longitude: 3.4448,
    description: '24/7 University emergency clinic, pharmacy, observation wards, and clinical laboratory for students and staff.',
    walkingTip: 'South of the central library; 24-hour emergency ambulance service stationed outside.',
  },
  {
    id: 'funaab-zenith-bank',
    name: 'Zenith Bank & 24/7 ATM Hub (Campus Branch)',
    shortCode: 'ZENITH-ATM',
    campus: 'FUNAAB',
    category: 'ATM & Bank',
    latitude: 7.2245,
    longitude: 3.4452,
    description: 'Full-service commercial bank branch with 4 multi-network ATMs and student financial support desks.',
    walkingTip: 'Commercial bank strip adjacent to the University Health Centre.',
  },
  {
    id: 'funaab-access-bank',
    name: 'Access Bank & E-Branch',
    shortCode: 'ACCESS-ATM',
    campus: 'FUNAAB',
    category: 'ATM & Bank',
    latitude: 7.2243,
    longitude: 3.4450,
    description: 'Commercial banking branch, instant debit card dispensation, and cash deposit ATMs.',
    walkingTip: 'Located along the commercial banking arcade opposite the Health Centre.',
  },
  {
    id: 'funaab-gtbank',
    name: 'GTBank E-Branch & Cash Desks',
    shortCode: 'GTB-ATM',
    campus: 'FUNAAB',
    category: 'ATM & Bank',
    latitude: 7.2247,
    longitude: 3.4449,
    description: 'Self-service digital banking hub and 24-hour illuminated cash dispenser kiosks.',
    walkingTip: 'Next to Zenith Bank on the commercial banking strip.',
  },
  {
    id: 'funaab-sug-secretariat',
    name: 'Student Union Government (SUG) Secretariat & Food Court',
    shortCode: 'SUG',
    campus: 'FUNAAB',
    category: 'Food & Social',
    latitude: 7.2252,
    longitude: 3.4440,
    description: 'Vibrant student union hub, executive council chambers, multi-vendor food canteen, and printing services.',
    walkingTip: 'Directly on Motion Ground; popular student convergence point between lectures.',
  },
  {
    id: 'funaab-motion-ground',
    name: 'Motion Ground (Central Quadrangle)',
    shortCode: 'MOTION',
    campus: 'FUNAAB',
    category: 'Food & Social',
    latitude: 7.2254,
    longitude: 3.4430,
    description: 'The beating heart of student campus life, social gatherings, career fairs, awareness walks, and matriculation photos.',
    walkingTip: 'The main paved lawn bounded by the Senate Building, Library, and SUG building.',
  },
  {
    id: 'funaab-sports-complex',
    name: 'FUNAAB Sports Complex & Stadium',
    shortCode: 'STADIUM',
    campus: 'FUNAAB',
    category: 'Sports',
    latitude: 7.2272,
    longitude: 3.4390,
    description: 'Main football pitch, synthetic athletics track, basketball courts, volleyball, and tennis arena.',
    walkingTip: 'West campus avenue, past the Ceremonial Building.',
  },
  {
    id: 'funaab-tinubu-hostel',
    name: 'Iyalode Tinubu Hall of Residence (ITH)',
    shortCode: 'TINUBU',
    campus: 'FUNAAB',
    category: 'Hostel',
    latitude: 7.2290,
    longitude: 3.4475,
    description: 'Major female undergraduate hall of residence with internal study rooms, buttery, and cafeteria.',
    walkingTip: 'North-eastern residential sector; serviced by the internal shuttle bus.',
  },
  {
    id: 'funaab-umar-kabir-hostel',
    name: 'Umar-Kabir Hall of Residence (Male Hostel)',
    shortCode: 'UMAR-KABIR',
    campus: 'FUNAAB',
    category: 'Hostel',
    latitude: 7.2292,
    longitude: 3.4485,
    description: 'Prominent undergraduate male hall of residence with sports courtyard and communal study lounge.',
    walkingTip: 'Hostel quadrangle adjacent to ITH in the northern residential sector.',
  },
  {
    id: 'funaab-babatunde-hostel',
    name: 'Professor Babatunde Male Hostel',
    shortCode: 'BABATUNDE',
    campus: 'FUNAAB',
    category: 'Hostel',
    latitude: 7.2298,
    longitude: 3.4465,
    description: 'Undergraduate male hall of residence with recreational common rooms and sports court.',
    walkingTip: 'Residential quadrangle adjacent to Iyalode Tinubu Hall.',
  },
  {
    id: 'funaab-new-female-hostel',
    name: 'New Female Hall of Residence (Moremi Annex)',
    shortCode: 'MOREMI-ANNEX',
    campus: 'FUNAAB',
    category: 'Hostel',
    latitude: 7.2295,
    longitude: 3.4470,
    description: 'Modern female hostel block with en-suite amenities and dedicated study cubicles.',
    walkingTip: 'Located along the hostel ring road facing ITH.',
  },
  {
    id: 'funaab-pg-hostel',
    name: 'Postgraduate Hall of Residence',
    shortCode: 'PG-HALL',
    campus: 'FUNAAB',
    category: 'Hostel',
    latitude: 7.2305,
    longitude: 3.4480,
    description: 'En-suite study accommodations for Master and PhD research scholars.',
    walkingTip: 'Northern boundary of the student residential sector.',
  },
  {
    id: 'funaab-dufarms',
    name: 'DUFARMS (Directorate of University Farms) & Farm Centre',
    shortCode: 'DUFARMS',
    campus: 'FUNAAB',
    category: 'Administrative',
    latitude: 7.2205,
    longitude: 3.4405,
    description: 'Commercial university farm complex, poultry units, fisheries, crop processing mills, and Farm Practical Year (FPY) centre.',
    walkingTip: 'South-western agricultural sector past COLVET.',
  },
  {
    id: 'funaab-main-gate',
    name: 'FUNAAB Ceremonial Main Gate & Shuttle Park',
    shortCode: 'MAIN-GATE',
    campus: 'FUNAAB',
    category: 'Administrative',
    latitude: 7.2185,
    longitude: 3.4350,
    description: 'University main security checkpoint, visitor registration, and campus green-and-white shuttle hub.',
    walkingTip: 'Main entrance off Alabata Road; starting point for all campus shuttle transit.',
  },
  {
    id: 'funaab-camp-junction',
    name: 'Camp Junction Terminal & Student Market',
    shortCode: 'CAMP-JUNCTION',
    campus: 'FUNAAB',
    category: 'Food & Social',
    latitude: 7.2020,
    longitude: 3.4150,
    description: 'Major student off-campus transit interchange, yellow cab depot, bookshops, markets, and off-campus student hub.',
    walkingTip: 'At the Camp roundabout; boarding point for university shuttle buses entering campus.',
  },
  {
    id: 'funaab-zoo-park',
    name: 'FUNAAB Zoological Garden & Eco-Park',
    shortCode: 'ZOO',
    campus: 'FUNAAB',
    category: 'Food & Social',
    latitude: 7.2195,
    longitude: 3.4380,
    description: 'Conservation park, animal reserve, botanical relaxation area, and picnic grounds.',
    walkingTip: 'Along the driveway between the Main Gate and the central campus quad.',
  },

  // UNIVERSITY OF IBADAN (UI)
  {
    id: 'ui-trenchard-hall',
    name: 'Trenchard Hall & Tower Court',
    shortCode: 'TH',
    campus: 'UI',
    category: 'Administrative',
    latitude: 7.4485,
    longitude: 3.8995,
    description: 'Historic convocation amphitheatre, matriculation ceremonies, and university-wide symposiums.',
    walkingTip: 'Central location right next to the Senate Building and the main gate driveway.',
  },
  {
    id: 'ui-senate-building',
    name: 'University Senate Building (Tekena Tamuno Building)',
    shortCode: 'SENATE',
    campus: 'UI',
    category: 'Administrative',
    latitude: 7.4478,
    longitude: 3.8992,
    description: "Administrative headquarters housing the Vice-Chancellor's Secretariat, Academic Affairs, and Registry.",
    walkingTip: 'Directly facing the main university driveway, fountain court, and Trenchard Hall.',
  },
  {
    id: 'ui-kenneth-dike-lib',
    name: 'Kenneth Dike Memorial Central Library (KDL)',
    shortCode: 'KDL',
    campus: 'UI',
    category: 'Library',
    latitude: 7.4468,
    longitude: 3.9002,
    description: 'Premier university research library in West Africa housing extensive Africana archives, millions of manuscripts, and digital reading rooms.',
    walkingTip: '1-minute walk south of Trenchard Hall across the palm-tree avenue.',
  },
  {
    id: 'ui-cbn-lt',
    name: 'J. Oladele Sanusi Lecture Theatre (CBN Lecture Theatre)',
    shortCode: 'CBN-LT',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4480,
    longitude: 3.9015,
    description: 'Massive multi-tiered central lecture auditorium for 100-level university general courses, GST tests, and academic assemblies.',
    walkingTip: 'Located near the Faculty of Science quadrangle along science road.',
  },
  {
    id: 'ui-subomi-balogun-centre',
    name: 'Otunba Subomi Balogun Conference Centre',
    shortCode: 'SUBOMI-CTR',
    campus: 'UI',
    category: 'Administrative',
    latitude: 7.4505,
    longitude: 3.8990,
    description: 'Modern multi-purpose conference, banquet, and academic symposium facility named after Otunba Subomi Balogun.',
    walkingTip: 'Northern academic quadrangle near the Faculty of Law and Education avenue.',
  },
  {
    id: 'ui-international-conference-centre',
    name: 'UI International Conference Centre (ICC)',
    shortCode: 'UI-ICC',
    campus: 'UI',
    category: 'Administrative',
    latitude: 7.4550,
    longitude: 3.9050,
    description: 'Grand 5,000-seat national conference centre and international event arena.',
    walkingTip: 'North-east campus quadrant along the second gate road.',
  },
  {
    id: 'ui-sub',
    name: 'Student Union Building (SUB & Kunle Adepeju Building)',
    shortCode: 'SUB',
    campus: 'UI',
    category: 'Food & Social',
    latitude: 7.4449,
    longitude: 3.8988,
    description: 'Student governance secretariat, central cafeteria food court, printing shops, stationery stores, and banking gallery.',
    walkingTip: 'Beside Sultan Bello Hall; central food and student activity hub.',
  },
  {
    id: 'ui-first-bank-atm',
    name: 'First Bank & ATM Gallery (SUB)',
    shortCode: 'FBN-ATM',
    campus: 'UI',
    category: 'ATM & Bank',
    latitude: 7.4451,
    longitude: 3.8986,
    description: 'Multi-machine 24/7 ATM gallery and student banking services.',
    walkingTip: 'Adjacent to SUB car park and central student secretariat.',
  },
  {
    id: 'ui-gtbank-sub',
    name: 'GTBank Campus Branch & E-Branch',
    shortCode: 'GTB-UI',
    campus: 'UI',
    category: 'ATM & Bank',
    latitude: 7.4454,
    longitude: 3.8990,
    description: 'Self-service cash deposit machines, student accounts desk, and fast teller stations.',
    walkingTip: 'Across from the Faculty of Arts car park.',
  },
  {
    id: 'ui-faculty-arts',
    name: 'Faculty of Arts Complex & Arts Theatre',
    shortCode: 'ARTS',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4460,
    longitude: 3.8998,
    description: 'Linguistics, English, History, Classics, Philosophy lecture halls, and the iconic Geoffrey Axworthy Arts Theatre.',
    walkingTip: 'Directly across from Kenneth Dike Memorial Library.',
  },
  {
    id: 'ui-faculty-science-nlh',
    name: 'Faculty of Science Complex & New Lecture Hall (NLH)',
    shortCode: 'SCIENCE-NLH',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4482,
    longitude: 3.9025,
    description: 'Mathematics, Physics, Chemistry, Computer Science, Statistics, and Geology lecture auditoriums and laboratories.',
    walkingTip: 'Adjacent to Chemistry labs and the faculty botanical quad.',
  },
  {
    id: 'ui-faculty-tech-llt',
    name: 'Large Lecture Theatre (LLT) - Faculty of Technology',
    shortCode: 'TECH-LLT',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4498,
    longitude: 3.9042,
    description: 'Multi-tiered 800-seat lecture auditorium for Electrical, Mechanical, Civil, Industrial, and Agricultural Engineering.',
    walkingTip: 'Behind Faculty of Technology quad; 4-minute walk eastward from KDL.',
  },
  {
    id: 'ui-faculty-social-sciences',
    name: 'Faculty of the Social Sciences & Large Lecture Theatre',
    shortCode: 'FSS',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4455,
    longitude: 3.9020,
    description: 'Economics, Political Science, Sociology, Psychology, and Geography lecture theatres and seminar rooms.',
    walkingTip: 'South of the Science complex, opposite Queen Elizabeth Hall avenue.',
  },
  {
    id: 'ui-faculty-agriculture',
    name: 'Faculty of Agriculture & Forestry Complex',
    shortCode: 'AGRIC',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4475,
    longitude: 3.9035,
    description: 'Agronomy, Animal Science, Crop Protection, Agricultural Economics, and farm research pilot halls.',
    walkingTip: 'East of Kenneth Dike Library along the agricultural avenue.',
  },
  {
    id: 'ui-faculty-law',
    name: 'Faculty of Law & Law Lecture Theatre (Wole Olanipekun Hall)',
    shortCode: 'LAW',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4465,
    longitude: 3.8985,
    description: 'Jurisprudence, Commercial Law, specialized Law Library, and student moot courtrooms.',
    walkingTip: 'Short walk from Trenchard Hall along Niger Road.',
  },
  {
    id: 'ui-faculty-pharmacy',
    name: 'Faculty of Pharmacy Complex & Pharmacy Lecture Theatre',
    shortCode: 'PHARMACY',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4490,
    longitude: 3.9030,
    description: 'Pharmaceutical Chemistry, Pharmaceutics, Pharmacognosy, and Pharmacology laboratories and lecture halls.',
    walkingTip: 'Northeast of Faculty of Science along Tech road.',
  },
  {
    id: 'ui-faculty-education',
    name: 'Faculty of Education & Large Lecture Theatre',
    shortCode: 'EDUCATION',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4445,
    longitude: 3.9015,
    description: 'Educational Management, Guidance & Counseling, Adult Education, Teacher Education, and Library Studies auditoriums.',
    walkingTip: 'South of Faculty of Arts along the botanical drive.',
  },
  {
    id: 'ui-faculty-vet',
    name: 'Faculty of Veterinary Medicine Complex & Clinic',
    shortCode: 'VET',
    campus: 'UI',
    category: 'Lecture Hall',
    latitude: 7.4488,
    longitude: 3.9048,
    description: 'Veterinary Anatomy, Pathology, Clinics, animal hospital, and diagnostic suites.',
    walkingTip: 'East academic quadrangle past Faculty of Technology.',
  },
  {
    id: 'ui-college-of-medicine',
    name: 'College of Medicine UI & University College Hospital (UCH)',
    shortCode: 'UI-UCH',
    campus: 'UI',
    category: 'Medical',
    latitude: 7.4045,
    longitude: 3.9025,
    description: 'Premier medical college and tertiary teaching hospital in Nigeria, housing clinical departments and medical libraries.',
    walkingTip: 'Located at Queen Elizabeth Road, Mokola; accessed via UI-UCH medical shuttle.',
  },
  {
    id: 'ui-jaja-clinic',
    name: 'Jaja University Health Services (Jaja Clinic)',
    shortCode: 'JAJA',
    campus: 'UI',
    category: 'Medical',
    latitude: 7.4435,
    longitude: 3.8990,
    description: '24/7 University emergency clinic, pharmacy, in-patient wards, and clinical laboratory for students and staff.',
    walkingTip: 'Down the avenue past Bello Hall and Staff Club; ambulance station on site.',
  },
  {
    id: 'ui-sports-complex',
    name: 'Awo Stadium & UI Sports Centre',
    shortCode: 'UI-STADIUM',
    campus: 'UI',
    category: 'Sports',
    latitude: 7.4460,
    longitude: 3.8945,
    description: 'Main athletics stadium, synthetic running track, Olympic swimming pool, squash, basketball, and tennis courts.',
    walkingTip: 'West of Obafemi Awolowo Hall along the sports drive.',
  },
  {
    id: 'ui-sultan-bello',
    name: 'Sultan Bello Hall of Residence',
    shortCode: 'BELLO',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4452,
    longitude: 3.8975,
    description: 'Historic undergraduate male hall of residence founded in 1962, celebrated as the "Gentlemen\'s Hall".',
    walkingTip: 'Right opposite Queen Elizabeth Hall and a 1-minute walk to SUB.',
  },
  {
    id: 'ui-mellanby-hall',
    name: 'Kenneth Mellanby Hall (Hall 1)',
    shortCode: 'MELLANBY',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4475,
    longitude: 3.8985,
    description: 'The premier hall of residence in Nigeria, opened in 1952 and named after UI\'s first Principal.',
    walkingTip: 'Adjacent to Tedder Hall directly across from Trenchard Hall.',
  },
  {
    id: 'ui-tedder-hall',
    name: 'Lord Tedder Hall (Hall 2)',
    shortCode: 'TEDDER',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4470,
    longitude: 3.8980,
    description: 'Historic undergraduate male hall of residence named after Lord Tedder.',
    walkingTip: 'Beside Mellanby Hall and directly opposite Trenchard Hall.',
  },
  {
    id: 'ui-kuti-hall',
    name: 'Kuti Hall of Residence',
    shortCode: 'KUTI',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4465,
    longitude: 3.8970,
    description: 'Male hall of residence named after Rev. I.O. Ransome-Kuti, with an active student community and sports quad.',
    walkingTip: 'Situated between Tedder Hall and Sultan Bello Hall.',
  },
  {
    id: 'ui-queen-elizabeth',
    name: 'Queen Elizabeth II Hall (Queen\'s Hall)',
    shortCode: 'QUEENS',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4445,
    longitude: 3.8970,
    description: 'Historic female undergraduate hall of residence opened by Queen Elizabeth II during her 1956 visit to Nigeria.',
    walkingTip: 'Directly opposite Sultan Bello Hall along Oduduwa Road.',
  },
  {
    id: 'ui-queen-idia',
    name: 'Queen Idia Hall of Residence',
    shortCode: 'IDIA',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4520,
    longitude: 3.9010,
    description: 'Premier female undergraduate hostel accommodation with large dining hall and study chambers.',
    walkingTip: 'Northern campus residential quad near the second gate.',
  },
  {
    id: 'ui-zik-hall',
    name: 'Nnamdi Azikiwe Hall (Zik Hall)',
    shortCode: 'ZIK',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4515,
    longitude: 3.8965,
    description: 'Iconic undergraduate male hall celebrated for its vibrant "Zikites" tradition and intellectual camaraderie.',
    walkingTip: 'Northwest residential district, adjacent to Independence Hall.',
  },
  {
    id: 'ui-independence-hall',
    name: 'Independence Hall (Indy Hall)',
    shortCode: 'INDY',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4510,
    longitude: 3.8955,
    description: 'Famous male undergraduate hall founded in 1960 to commemorate Nigerian independence (Katanga Republic).',
    walkingTip: 'Beside Zik Hall in the northwestern residential sector.',
  },
  {
    id: 'ui-awolowo-hall',
    name: 'Obafemi Awolowo Hall (Awo Hall)',
    shortCode: 'AWO',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4465,
    longitude: 3.8935,
    description: 'Large residential hall accommodating undergraduate and postgraduate female students.',
    walkingTip: 'West of the main academic campus; beside the UI Sports Stadium.',
  },
  {
    id: 'ui-alexander-brown',
    name: 'Alexander Brown Hall (ABH - UCH)',
    shortCode: 'ABH',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4040,
    longitude: 3.9030,
    description: 'Residential hall for clinical medical, dental, and nursing students situated within UCH Ibadan.',
    walkingTip: 'Located inside the University College Hospital complex on Queen Elizabeth Road.',
  },
  {
    id: 'ui-tafawa-balewa',
    name: 'Tafawa Balewa Postgraduate Hall',
    shortCode: 'BALEWA',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4480,
    longitude: 3.8970,
    description: 'Postgraduate hall of residence named after Sir Abubakar Tafawa Balewa.',
    walkingTip: 'Beside Mellanby and Tedder halls in the central residential area.',
  },
  {
    id: 'ui-abdulsalami-abubakar',
    name: 'Abdulsalami Abubakar Postgraduate Hall',
    shortCode: 'ABDULSALAMI',
    campus: 'UI',
    category: 'Hostel',
    latitude: 7.4525,
    longitude: 3.8980,
    description: 'Modern postgraduate residential complex for Master and PhD research scholars.',
    walkingTip: 'North campus area near Zik and Idia halls.',
  },
  {
    id: 'ui-zoo',
    name: 'UI Zoological Garden (UI Zoo)',
    shortCode: 'ZOO',
    campus: 'UI',
    category: 'Food & Social',
    latitude: 7.4440,
    longitude: 3.9040,
    description: 'Famous zoological garden and animal conservation sanctuary, a favorite recreational and research spot.',
    walkingTip: 'East of Faculty of Arts along Appleton Road.',
  },
  {
    id: 'ui-botanical-garden',
    name: 'UI Botanical Garden & Arboretum',
    shortCode: 'BOTANICAL',
    campus: 'UI',
    category: 'Food & Social',
    latitude: 7.4430,
    longitude: 3.9060,
    description: '100-acre tropical conservation garden, tranquil nature walks, open-air reading canopies, and research flora.',
    walkingTip: 'Past the UI Zoo on the eastern boundary of the university.',
  },
  {
    id: 'ui-heritage-park',
    name: 'UI Heritage Park & Love Garden',
    shortCode: 'HERITAGE-PK',
    campus: 'UI',
    category: 'Food & Social',
    latitude: 7.4430,
    longitude: 3.9005,
    description: 'Beautiful landscaped park, water fountain, shaded benches, and relaxation gardens for students.',
    walkingTip: 'Along the main driveway between the Ceremonial Main Gate and Trenchard Hall.',
  },
  {
    id: 'ui-main-gate',
    name: 'UI Ceremonial Main Gate',
    shortCode: 'MAIN-GATE',
    campus: 'UI',
    category: 'Administrative',
    latitude: 7.4420,
    longitude: 3.9010,
    description: 'Historic ceremonial entrance arch along Oyo Road, bus and taxi terminal, and university security post.',
    walkingTip: 'Primary access point into university grounds from Bodija / Sango.',
  },
  {
    id: 'ui-second-gate',
    name: 'UI Second Gate (Poly Road / Ajibode)',
    shortCode: 'SECOND-GATE',
    campus: 'UI',
    category: 'Administrative',
    latitude: 7.4560,
    longitude: 3.8940,
    description: 'Northern entrance gate providing direct transit to The Polytechnic Ibadan, Ojoo, and Ajibode.',
    walkingTip: 'Located at the northern perimeter beyond Queen Idia Hall.',
  },
  {
    id: 'ui-bookshop',
    name: 'UI Bookshop & University Publishing House',
    shortCode: 'BOOKSHOP',
    campus: 'UI',
    category: 'Food & Social',
    latitude: 7.4462,
    longitude: 3.8992,
    description: 'Official academic bookstore, university press, stationery depot, and reference textbook center.',
    walkingTip: 'Opposite Kenneth Dike Library along the central walkway.',
  },

  // UNIVERSITY OF LAGOS (UNILAG)
  {
    id: 'unilag-senate-house',
    name: 'UNILAG Senate House (13-Storey Tower)',
    shortCode: 'UNILAG-SENATE',
    campus: 'UNILAG',
    category: 'Administrative',
    latitude: 6.5168,
    longitude: 3.3980,
    description: "13-storey iconic administrative skyscraper housing the Vice-Chancellor's Secretariat, Academic Affairs, and Registry.",
    walkingTip: 'Central focal point of the university overlooking the Lagos Lagoon front.',
  },
  {
    id: 'unilag-main-auditorium',
    name: 'J.F. Ade Ajayi Auditorium (Main Auditorium)',
    shortCode: 'AUDITORIUM',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5180,
    longitude: 3.3970,
    description: '3,500-seat grand historic auditorium for convocations, matriculations, public lectures, and inaugural addresses.',
    walkingTip: 'Facing Senate House driveway; easily accessible by campus shuttle.',
  },
  {
    id: 'unilag-mph',
    name: 'Jelili Adebisi Omotola Hall (Multipurpose Hall / MPH)',
    shortCode: 'MPH',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5185,
    longitude: 3.3995,
    description: 'Multi-functional convention complex for university examinations, student trade fairs, conferences, and concerts.',
    walkingTip: 'Next to the UNILAG Sports Centre and Olympic indoor gymnasium.',
  },
  {
    id: 'unilag-afe-babalola',
    name: 'Afe Babalola Auditorium',
    shortCode: 'AFE-BABALOLA',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5162,
    longitude: 3.3992,
    description: 'Architecturally distinct triangular auditorium for academic colloquia, guest lectures, and departmental symposiums.',
    walkingTip: 'Situated between Senate House and the Faculty of Arts complex.',
  },
  {
    id: 'unilag-tayo-aderinokun',
    name: 'Tayo Aderinokun Memorial Lecture Theatre',
    shortCode: 'ADERINOKUN-LT',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5155,
    longitude: 3.3950,
    description: 'Ultra-modern 500-seat lecture auditorium for high-capacity undergraduate courses and professional seminars.',
    walkingTip: 'Near Faculty of Social Sciences and Management Sciences quadrangle.',
  },
  {
    id: 'unilag-julius-berger',
    name: 'Julius Berger Lecture Theatre & Civil Lab',
    shortCode: 'BERGER-HALL',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5165,
    longitude: 3.3945,
    description: 'Modern engineering amphitheatre and geotechnical testing auditorium built by Julius Berger.',
    walkingTip: 'Behind Faculty of Engineering along the western academic drive.',
  },
  {
    id: 'unilag-main-library',
    name: 'UNILAG Main Library (Yakubu Gowon Library)',
    shortCode: 'UNILAG-LIB',
    campus: 'UNILAG',
    category: 'Library',
    latitude: 6.5175,
    longitude: 3.3975,
    description: 'Multi-level academic research library with quiet study carrels, Africana archives, and digital e-learning labs.',
    walkingTip: 'Right opposite Senate House and J.F. Ade Ajayi Auditorium.',
  },
  {
    id: 'unilag-faculty-arts',
    name: 'Faculty of Arts Complex & Arts Theatre',
    shortCode: 'ARTS',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5160,
    longitude: 3.3985,
    description: 'English, Linguistics, History, Philosophy, and Creative Arts classrooms, workshops, and performance theatre.',
    walkingTip: 'Short walk from Senate House toward the lagoon walk.',
  },
  {
    id: 'unilag-faculty-science',
    name: 'Faculty of Science Complex & Science Quadrangle',
    shortCode: 'SCIENCE',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5172,
    longitude: 3.3960,
    description: 'Computer Science, Physics, Chemistry, Mathematics, Microbiology, and central faculty laboratories.',
    walkingTip: 'Central campus quadrangle across from Yakubu Gowon Library.',
  },
  {
    id: 'unilag-faculty-engineering',
    name: 'Faculty of Engineering Complex & Workshops',
    shortCode: 'ENG',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5160,
    longitude: 3.3940,
    description: 'Civil, Electrical, Mechanical, Chemical, Computer, and Petroleum Engineering departments, CAD labs, and machine shops.',
    walkingTip: 'Along Commercial Avenue heading west from Senate House.',
  },
  {
    id: 'unilag-faculty-law',
    name: 'Faculty of Law Complex & Justice Taslim Elias Moot Court',
    shortCode: 'LAW',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5150,
    longitude: 3.3970,
    description: 'Premier law faculty in West Africa, Law Library, moot courtroom, and Jurisprudence lecture theatres.',
    walkingTip: '2-minute stroll from Moremi Hall and Commercial Avenue.',
  },
  {
    id: 'unilag-faculty-social-sciences',
    name: 'Faculty of Social Sciences & 1000-Seater Lecture Hall',
    shortCode: 'FSS',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5145,
    longitude: 3.3955,
    description: 'Economics, Mass Communication, Political Science, Sociology, and Psychology lecture halls and studios.',
    walkingTip: 'Near Tayo Aderinokun Lecture Theatre on Commercial Avenue.',
  },
  {
    id: 'unilag-faculty-management-sciences',
    name: 'Faculty of Management Sciences (Business Administration)',
    shortCode: 'FMS',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5152,
    longitude: 3.3935,
    description: 'Accounting, Banking & Finance, Business Administration, and Industrial Relations lecture complexes.',
    walkingTip: 'Adjacent to Faculty of Environmental Sciences along the western academic corridor.',
  },
  {
    id: 'unilag-faculty-environmental-sciences',
    name: 'Faculty of Environmental Sciences & Architecture Studios',
    shortCode: 'ENV-SCI',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5158,
    longitude: 3.3930,
    description: 'Architecture design studios, Urban & Regional Planning, Building, Estate Management, and Quantity Surveying.',
    walkingTip: 'West academic avenue near Faculty of Engineering.',
  },
  {
    id: 'unilag-faculty-education',
    name: 'Faculty of Education Complex & Glass House',
    shortCode: 'EDU-GLASS',
    campus: 'UNILAG',
    category: 'Lecture Hall',
    latitude: 6.5135,
    longitude: 3.3940,
    description: 'Educational Foundations, Science & Tech Education, Adult Education, and the famous Glass House lecture theatre.',
    walkingTip: 'Southern academic corridor near Biobaku Hall.',
  },
  {
    id: 'unilag-dli',
    name: 'Distance Learning Institute (DLI) Complex',
    shortCode: 'DLI',
    campus: 'UNILAG',
    category: 'Administrative',
    latitude: 6.5125,
    longitude: 3.3930,
    description: 'Administrative and e-learning centre for distance and open-learning students of UNILAG.',
    walkingTip: 'Southern sector past Faculty of Education.',
  },
  {
    id: 'unilag-cits',
    name: 'CITS (Centre for Information Technology and Systems) & CBT Hall',
    shortCode: 'CITS-CBT',
    campus: 'UNILAG',
    category: 'Administrative',
    latitude: 6.5170,
    longitude: 3.3965,
    description: 'Central university ICT infrastructure, student computer-based testing (CBT) center, and network operations hub.',
    walkingTip: 'Behind the Faculty of Science quadrangle.',
  },
  {
    id: 'unilag-cmul',
    name: 'College of Medicine UNILAG (CMUL) - Idi-Araba',
    shortCode: 'CMUL',
    campus: 'UNILAG',
    category: 'Medical',
    latitude: 6.5245,
    longitude: 3.3595,
    description: 'Medical and dental school complex adjacent to Lagos University Teaching Hospital (LUTH).',
    walkingTip: 'Located at Idi-Araba, Surulere campus; accessed via university shuttle.',
  },
  {
    id: 'unilag-medical-centre',
    name: 'UNILAG Medical Health Centre',
    shortCode: 'MED-CENTRE',
    campus: 'UNILAG',
    category: 'Medical',
    latitude: 6.5132,
    longitude: 3.3955,
    description: '24/7 Student and staff health clinic, emergency ambulance bay, outpatient wards, and clinical pharmacy.',
    walkingTip: 'Beside staff quarters along Commercial Road.',
  },
  {
    id: 'unilag-mariere',
    name: 'Jerome Mariere Hall (Male Hostel)',
    shortCode: 'MARIERE',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5140,
    longitude: 3.3970,
    description: 'Central undergraduate male hostel with active sports courtyard and student buttery.',
    walkingTip: 'Short walk to commercial bank square and shuttle park.',
  },
  {
    id: 'unilag-moremi',
    name: 'Moremi Hall of Residence (Female Hostel)',
    shortCode: 'MOREMI',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5152,
    longitude: 3.3960,
    description: 'Flagship female undergraduate hall adjacent to the lagoon botanical walk.',
    walkingTip: '2-minute stroll from the Faculty of Law building.',
  },
  {
    id: 'unilag-amina',
    name: 'Queen Amina Hall (Female Hostel)',
    shortCode: 'AMINA',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5148,
    longitude: 3.3975,
    description: 'Female undergraduate hall of residence with study rooms and inner courtyard.',
    walkingTip: 'Across from Mariere Hall along the central hostel avenue.',
  },
  {
    id: 'unilag-jaja',
    name: 'King Jaja Hall of Residence (Male Hostel)',
    shortCode: 'JAJA',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5135,
    longitude: 3.3965,
    description: 'Popular male undergraduate hostel named after King Jaja of Opobo.',
    walkingTip: 'Adjacent to Mariere Hall near the health centre.',
  },
  {
    id: 'unilag-kofo-ademola',
    name: 'Kofo Ademola Hall (Female Hostel)',
    shortCode: 'KOFO',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5128,
    longitude: 3.3960,
    description: 'Female undergraduate residence situated in the New Hall residential quadrangle.',
    walkingTip: 'Located inside the New Hall hostel complex.',
  },
  {
    id: 'unilag-eni-njoku',
    name: 'Eni-Njoku Hall (Male Hostel - New Hall)',
    shortCode: 'ENI-NJOKU',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5195,
    longitude: 3.3960,
    description: "Male undergraduate hall named after UNILAG's first Vice-Chancellor, situated in New Hall.",
    walkingTip: 'Inside the New Hall student residential district.',
  },
  {
    id: 'unilag-makama-bida',
    name: 'Makama Bida Hall (New Hall)',
    shortCode: 'MAKAMA',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5198,
    longitude: 3.3955,
    description: 'Male hall of residence in the New Hall student residential enclave.',
    walkingTip: 'Beside Eni-Njoku Hall in New Hall.',
  },
  {
    id: 'unilag-fagunwa',
    name: 'Fagunwa Hall (Female Hostel - New Hall)',
    shortCode: 'FAGUNWA',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5202,
    longitude: 3.3965,
    description: 'Female undergraduate residence hall in the New Hall complex.',
    walkingTip: 'Directly opposite Eni-Njoku Hall in New Hall.',
  },
  {
    id: 'unilag-madam-tinubu',
    name: 'Madam Tinubu Hall (MTH - Female Hostel)',
    shortCode: 'MTH',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5205,
    longitude: 3.3970,
    description: 'High-density female undergraduate hall of residence in New Hall.',
    walkingTip: 'Northern quadrant of New Hall.',
  },
  {
    id: 'unilag-biobaku',
    name: 'Saburi Biobaku Hall (Male Hostel)',
    shortCode: 'BIOBAKU',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5120,
    longitude: 3.3950,
    description: 'Undergraduate male residence near the Faculty of Education.',
    walkingTip: 'Southern campus corridor along Education road.',
  },
  {
    id: 'unilag-el-kanemi',
    name: 'El-Kanemi Hall (Male Hostel)',
    shortCode: 'EL-KANEMI',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5115,
    longitude: 3.3945,
    description: 'Male hall of residence located near the second gate.',
    walkingTip: 'Short walk to the Iwaya exit gate.',
  },
  {
    id: 'unilag-gbajabiamila',
    name: 'Femi Gbajabiamila International Hall of Residence',
    shortCode: 'GBAJABIAMILA',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5210,
    longitude: 3.3980,
    description: 'Ultra-modern 484-bed international student hostel complex with contemporary student amenities.',
    walkingTip: 'Past the New Hall complex along the lagoon perimeter road.',
  },
  {
    id: 'unilag-henry-carr',
    name: 'Henry Carr Postgraduate Hall',
    shortCode: 'HENRY-CARR',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5200,
    longitude: 3.3975,
    description: 'Postgraduate accommodation for Master and Doctoral scholars.',
    walkingTip: 'New Hall north perimeter.',
  },
  {
    id: 'unilag-sodeinde',
    name: 'Sodeinde Hall of Residence',
    shortCode: 'SODEINDE',
    campus: 'UNILAG',
    category: 'Hostel',
    latitude: 6.5192,
    longitude: 3.3962,
    description: 'Multi-storey modern student hostel in the New Hall quadrangle.',
    walkingTip: 'Next to Eni-Njoku Hall in New Hall.',
  },
  {
    id: 'unilag-lagoon-front',
    name: 'UNILAG Lagoon Front Park & Love Garden',
    shortCode: 'LAGOON',
    campus: 'UNILAG',
    category: 'Food & Social',
    latitude: 6.5182,
    longitude: 3.4012,
    description: 'Scenic waterfront park, relaxation lawns, and open-air student study hub overlooking Lagos Lagoon.',
    walkingTip: 'Directly behind Senate House overlooking the water.',
  },
  {
    id: 'unilag-sports-centre',
    name: 'UNILAG Sports Centre & Olympic Swimming Pool',
    shortCode: 'SPORTS',
    campus: 'UNILAG',
    category: 'Sports',
    latitude: 6.5190,
    longitude: 3.3985,
    description: 'Olympic swimming pool, running track, football stadium, tennis courts, and indoor basketball gym.',
    walkingTip: 'Beside the Jelili Omotola Multipurpose Hall.',
  },
  {
    id: 'unilag-sub',
    name: 'UNILAG Student Union Building (SUB) & Commercial Arcade',
    shortCode: 'SUB',
    campus: 'UNILAG',
    category: 'Food & Social',
    latitude: 6.5145,
    longitude: 3.3965,
    description: 'Student union governance offices, bookstore, food vendors, photocopiers, and student relaxation hub.',
    walkingTip: 'Opposite Mariere Hall along Commercial Avenue.',
  },
  {
    id: 'unilag-main-gate',
    name: 'UNILAG Ceremonial Main Gate (University Road)',
    shortCode: 'MAIN-GATE',
    campus: 'UNILAG',
    category: 'Administrative',
    latitude: 6.5120,
    longitude: 3.3885,
    description: 'Primary security checkpoint, visitor registration, and campus entrance from Akoka and Yaba.',
    walkingTip: 'Primary access point into university grounds.',
  },
  {
    id: 'unilag-second-gate',
    name: 'UNILAG Second Gate (Iwaya Gate)',
    shortCode: 'SECOND-GATE',
    campus: 'UNILAG',
    category: 'Administrative',
    latitude: 6.5105,
    longitude: 3.3930,
    description: 'Secondary vehicular and pedestrian access gate connecting campus to Iwaya / Onike.',
    walkingTip: 'Southern perimeter near El-Kanemi Hall.',
  },
  {
    id: 'unilag-bank-strip',
    name: 'Commercial Bank Strip & ATM Hub (Access, Zenith, GTBank, UBA)',
    shortCode: 'BANKS',
    campus: 'UNILAG',
    category: 'ATM & Bank',
    latitude: 6.5158,
    longitude: 3.3965,
    description: 'Central multi-bank commercial strip with 24-hour illuminated ATMs and student financial service desks.',
    walkingTip: 'On the main commercial avenue opposite Faculty of Arts.',
  },
  {
    id: 'unilag-guest-houses',
    name: 'UNILAG Guest Houses & Conference Hotel',
    shortCode: 'GUEST-HOUSE',
    campus: 'UNILAG',
    category: 'Food & Social',
    latitude: 6.5170,
    longitude: 3.4005,
    description: 'University hospitality suites, international conference halls, and waterfront restaurant.',
    walkingTip: 'Along the lagoon front avenue beside Jelili Omotola Hall.',
  },

  // OBAFEMI AWOLOWO UNIVERSITY (OAU)
  {
    id: 'oau-oduduwa-hall',
    name: 'Oduduwa Hall & Amphitheatre',
    shortCode: 'ODUDUWA',
    campus: 'OAU',
    category: 'Lecture Hall',
    latitude: 7.5195,
    longitude: 4.5285,
    description: 'Architectural masterpiece amphitheatre for campus concerts and convocations.',
    walkingTip: 'Heart of campus quadrangle facing Hezekiah Oluwasanmi Library.',
  },
  {
    id: 'oau-hezekiah-library',
    name: 'Hezekiah Oluwasanmi Library',
    shortCode: 'HEZEKIAH',
    campus: 'OAU',
    category: 'Library',
    latitude: 7.5188,
    longitude: 4.5272,
    description: 'Legendary multi-tiered university academic and research repository.',
    walkingTip: 'Center of central university walkway opposite the Senate Building.',
  },
  {
    id: 'oau-senate-building',
    name: 'OAU Senate Building',
    shortCode: 'SENATE',
    campus: 'OAU',
    category: 'Administrative',
    latitude: 7.5190,
    longitude: 4.5280,
    description: 'Central administrative skyscraper housing the Vice-Chancellor secretariat.',
    walkingTip: 'Towering landmark in the central campus quadrangle.',
  },
  {
    id: 'oau-health-centre',
    name: 'OAU Student Health Centre',
    shortCode: 'OAU-HEALTH',
    campus: 'OAU',
    category: 'Medical',
    latitude: 7.515,
    longitude: 4.526,
    description: 'University hospital and 24/7 student pharmacy and clinical care.',
    walkingTip: 'Located near Road 1 and the sports complex.',
  },
  {
    id: 'oau-angola-hall',
    name: 'Angola Hall of Residence',
    shortCode: 'ANGOLA',
    campus: 'OAU',
    category: 'Hostel',
    latitude: 7.5220,
    longitude: 4.5310,
    description: 'Freshman male hall of residence with vibrant community life.',
    walkingTip: 'Adjacent to Mozambique Hall.',
  },
  {
    id: 'oau-mozambique-hall',
    name: 'Mozambique Hall of Residence',
    shortCode: 'MOZ',
    campus: 'OAU',
    category: 'Hostel',
    latitude: 7.5215,
    longitude: 4.5320,
    description: 'Freshman female hall of residence.',
    walkingTip: 'Behind the Student Union Building.',
  },
  {
    id: 'oau-sub',
    name: 'OAU Student Union Building (Ken Saro-Wiwa Block)',
    shortCode: 'SUB',
    campus: 'OAU',
    category: 'Food & Social',
    latitude: 7.5200,
    longitude: 4.5290,
    description: 'SUG chambers, student canteen arcade, bookshops, and social terrace.',
    walkingTip: 'Short walk east of Oduduwa Hall.',
  },
  {
    id: 'oau-banking-hall',
    name: 'OAU Central Banking Strip & ATMs',
    shortCode: 'BANKS',
    campus: 'OAU',
    category: 'ATM & Bank',
    latitude: 7.5175,
    longitude: 4.5265,
    description: 'Commercial banking branches including Wema, First Bank, and GTBank.',
    walkingTip: 'Along the main avenue toward the campus gate.',
  },

  // COVENANT UNIVERSITY (CU)
  {
    id: 'cu-cst-hall',
    name: 'College of Science & Technology (CST)',
    shortCode: 'CU-CST',
    campus: 'CU',
    category: 'Lecture Hall',
    latitude: 6.673,
    longitude: 3.1625,
    description: 'Computer Science, Electrical Engineering and Computational Labs.',
    walkingTip: 'Facing the campus central quadrangle and e-learning centre.',
  },
  {
    id: 'cu-clr-library',
    name: 'Centre for Learning Resources (CLR)',
    shortCode: 'CU-CLR',
    campus: 'CU',
    category: 'Library',
    latitude: 6.6715,
    longitude: 3.1605,
    description: 'Ultra-modern 3-storey digital library with automated study cubicles.',
    walkingTip: 'Adjacent to Senate Building and Chapel.',
  },
  {
    id: 'cu-senate-building',
    name: 'Covenant University Senate Building',
    shortCode: 'SENATE',
    campus: 'CU',
    category: 'Administrative',
    latitude: 6.6720,
    longitude: 3.1610,
    description: 'Administrative offices, Registrar, and Academic Planning Directorate.',
    walkingTip: 'Central axis of the Canaanland campus.',
  },
  {
    id: 'cu-health-centre',
    name: 'Covenant University Medical Centre',
    shortCode: 'HEALTH',
    campus: 'CU',
    category: 'Medical',
    latitude: 6.6705,
    longitude: 3.1595,
    description: 'Round-the-clock student and staff hospital with on-site pharmacy.',
    walkingTip: 'South of the residential halls.',
  },
  {
    id: 'cu-cafeteria-1',
    name: 'Student Cafeteria & Buttery 1',
    shortCode: 'CAFE',
    campus: 'CU',
    category: 'Food & Social',
    latitude: 6.6725,
    longitude: 3.1630,
    description: 'Main student dining hall, fruit market, and stationery shops.',
    walkingTip: 'Conveniently situated between male and female halls.',
  },
  {
    id: 'cu-stadium',
    name: 'Covenant Sports Complex',
    shortCode: 'STADIUM',
    campus: 'CU',
    category: 'Sports',
    latitude: 6.6740,
    longitude: 3.1640,
    description: 'Standard soccer stadium, basketball courts, and tartan track.',
    walkingTip: 'Behind the College of Engineering.',
  },

  // UNIVERSITY OF NIGERIA, NSUKKA (UNN)
  {
    id: 'unn-nnamdi-azikiwe-lib',
    name: 'Nnamdi Azikiwe Central Library',
    shortCode: 'UNN-LIB',
    campus: 'UNN',
    category: 'Library',
    latitude: 6.8675,
    longitude: 7.4115,
    description: 'One of the largest university research libraries in West Africa.',
    walkingTip: 'Heart of campus facing Freedom Square.',
  },
  {
    id: 'unn-senate-building',
    name: 'UNN Senate Building',
    shortCode: 'SENATE',
    campus: 'UNN',
    category: 'Administrative',
    latitude: 6.8665,
    longitude: 7.4105,
    description: 'Vice-Chancellor secretariat, Council Chambers, and Registry.',
    walkingTip: 'Opposite Freedom Square.',
  },
  {
    id: 'unn-medical-centre',
    name: 'UNN University Health Services',
    shortCode: 'HEALTH',
    campus: 'UNN',
    category: 'Medical',
    latitude: 6.8650,
    longitude: 7.4090,
    description: '24-hour emergency medical care, maternity, and pharmacy.',
    walkingTip: 'Along Franco avenue.',
  },
  {
    id: 'unn-sub',
    name: 'UNN Student Union Building & Franco Refectory',
    shortCode: 'SUB',
    campus: 'UNN',
    category: 'Food & Social',
    latitude: 6.8680,
    longitude: 7.4125,
    description: 'Student activities center, dining halls, and student council chambers.',
    walkingTip: 'East of the main quadrangle.',
  },

  // FEDERAL UNIVERSITY OF TECHNOLOGY, AKURE (FUTA)
  {
    id: 'futa-albert-ihemba-lib',
    name: 'Albert Ilemobade Central Library',
    shortCode: 'FUTA-LIB',
    campus: 'FUTA',
    category: 'Library',
    latitude: 7.3050,
    longitude: 5.1390,
    description: 'State-of-the-art technological library and e-learning hub.',
    walkingTip: 'Main campus avenue facing Senate Building.',
  },
  {
    id: 'futa-senate-building',
    name: 'FUTA Senate Building',
    shortCode: 'SENATE',
    campus: 'FUTA',
    category: 'Administrative',
    latitude: 7.3045,
    longitude: 5.1384,
    description: 'Administrative tower, Academic Affairs, and Bursary.',
    walkingTip: 'Central axis of the Obanla campus.',
  },
  {
    id: 'futa-seet-complex',
    name: 'School of Engineering & Engineering Tech (SEET)',
    shortCode: 'SEET',
    campus: 'FUTA',
    category: 'Lecture Hall',
    latitude: 7.3060,
    longitude: 5.1405,
    description: 'Engineering lecture halls, workshops, and computer laboratory.',
    walkingTip: 'Behind the library along SEET road.',
  },
  {
    id: 'futa-health-centre',
    name: 'FUTA Health Centre',
    shortCode: 'HEALTH',
    campus: 'FUTA',
    category: 'Medical',
    latitude: 7.3030,
    longitude: 5.1370,
    description: 'Student medical diagnostics, outpatient clinic, and emergency service.',
    walkingTip: 'Near the campus second gate.',
  },

  // AHMADU BELLO UNIVERSITY (ABU)
  {
    id: 'abu-kashim-ibrahim-lib',
    name: 'Kashim Ibrahim Library',
    shortCode: 'KIL',
    campus: 'ABU',
    category: 'Library',
    latitude: 11.1565,
    longitude: 7.6505,
    description: 'Premier Northern university academic research repository.',
    walkingTip: 'Central Samaru campus opposite Senate Building.',
  },
  {
    id: 'abu-senate-building',
    name: 'ABU Senate Building',
    shortCode: 'SENATE',
    campus: 'ABU',
    category: 'Administrative',
    latitude: 11.1558,
    longitude: 7.6497,
    description: 'Administrative headquarters of Ahmadu Bello University.',
    walkingTip: 'Heart of Samaru campus.',
  },
  {
    id: 'abu-assembly-hall',
    name: 'ABU Assembly Hall',
    shortCode: 'ASSEMBLY',
    campus: 'ABU',
    category: 'Lecture Hall',
    latitude: 11.1570,
    longitude: 7.6515,
    description: 'Historic matriculation, convocation, and student examination amphitheatre.',
    walkingTip: 'Beside Kashim Ibrahim Library.',
  },
  {
    id: 'abu-university-health-centre',
    name: 'ABU University Health Services (Sick Bay)',
    shortCode: 'HEALTH',
    campus: 'ABU',
    category: 'Medical',
    latitude: 11.1540,
    longitude: 7.6480,
    description: '24/7 University health center and clinical pharmacy.',
    walkingTip: 'Located along Suleiman Hall road.',
  },
];

/**
 * Calculates straight-line distance in meters between two geocoordinates using the Haversine formula.
 */
export function calculateDistanceMeters(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371000; // metres
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c);
}

/**
 * Formats distance in meters into human-readable metric and walking ETA (80 meters/min).
 */
export function formatDistanceAndEta(meters: number): { distanceText: string; etaText: string } {
  const distanceText = meters >= 1000 ? `${(meters / 1000).toFixed(1)} km` : `${meters} m`;
  const minutes = Math.max(1, Math.round(meters / 80));
  const etaText = minutes === 1 ? '1 min walk' : `${minutes} min walk`;
  return { distanceText, etaText };
}

/**
 * Queries OpenStreetMap (Overpass) for live amenities (ATMs, food, health, study areas) around a campus.
 *
 * The request goes through the `overpass-proxy` Supabase edge function: overpass-api.de answers any
 * browser User-Agent with a 406 that has no CORS headers, so a direct browser call can never succeed.
 * Results are cached per campus for 30 minutes because the upstream is slow (10-20s).
 */
const OVERPASS_PROXY_URL = `${process.env.EXPO_PUBLIC_SUPABASE_URL || 'https://fdtnbluslkabwsmspbem.supabase.co'}/functions/v1/overpass-proxy`;
const OVERPASS_PROXY_KEY = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || 'sb_publishable_TB0Pw8k2oJQTmoO951YaIQ_xzOyGpZF';
const OVERPASS_CACHE_TTL_MS = 30 * 60 * 1000;
const overpassCache = new Map<string, { at: number; data: any }>();

export async function fetchOverpassCampusAmenities(
  campusCode: string,
  userLat?: number,
  userLon?: number
): Promise<CampusLandmark[]> {
  const normalizedCampus = (campusCode && campusCode !== 'GLOBAL' ? campusCode : 'UNILAG').toUpperCase();
  const center = CAMPUS_CENTERS[normalizedCampus] || CAMPUS_CENTERS.UNILAG || CAMPUS_CENTERS.UI;
  const centerLat = center.latitude;
  const centerLon = center.longitude;

  try {
    let data: any = null;
    const cached = overpassCache.get(normalizedCampus);
    if (cached && Date.now() - cached.at < OVERPASS_CACHE_TTL_MS) {
      data = cached.data;
    } else {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 45000);
      try {
        const res = await fetch(OVERPASS_PROXY_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', apikey: OVERPASS_PROXY_KEY },
          body: JSON.stringify({ lat: centerLat, lon: centerLon }),
          signal: controller.signal,
        });
        if (res.ok) {
          data = await res.json();
          overpassCache.set(normalizedCampus, { at: Date.now(), data });
        }
      } finally {
        clearTimeout(timer);
      }
    }

    if (data) {
      const elements: any[] = data.elements || [];

      const liveLandmarks = elements
        .filter((el: any) => el.tags && (el.tags.name || el.tags.amenity || el.tags.operator))
        .map((el: any) => {
          const lat = el.lat || el.center?.lat || centerLat;
          const lon = el.lon || el.center?.lon || centerLon;
          const amenity = el.tags.amenity || '';
          const name = el.tags.name || el.tags.operator || `${amenity.toUpperCase()} Point`;

          let category: CampusLandmark['category'] = 'Administrative';
          if (amenity === 'atm' || amenity === 'bank') category = 'ATM & Bank';
          else if (amenity === 'clinic' || amenity === 'pharmacy' || amenity === 'hospital') category = 'Medical';
          else if (amenity === 'cafe' || amenity === 'restaurant' || amenity === 'fast_food') category = 'Food & Social';
          else if (amenity === 'library') category = 'Library';
          else if (el.tags.building === 'university' || el.tags.building === 'college') category = 'Lecture Hall';

          const dist = calculateDistanceMeters(
            userLat || centerLat,
            userLon || centerLon,
            lat,
            lon
          );

          return {
            id: `osm-${el.id}`,
            name,
            campus: normalizedCampus,
            category,
            latitude: lat,
            longitude: lon,
            description: el.tags['description'] || el.tags['addr:street'] || `Verified OpenStreetMap ${category} on campus.`,
            walkingTip: el.tags['opening_hours'] ? `Hours: ${el.tags['opening_hours']}` : 'Open to campus community',
            amenityType: amenity,
            isOsmLive: true,
            distanceMeters: dist,
          };
        });

      if (liveLandmarks.length > 0) {
        const local = getCampusLandmarks(normalizedCampus);
        const combined = [...local, ...liveLandmarks];
        const seen = new Set<string>();
        return combined.filter((item: CampusLandmark) => {
          if (item.campus.toUpperCase() !== normalizedCampus) return false;
          const key = item.name.toLowerCase().trim();
          if (seen.has(key)) return false;
          seen.add(key);
          return true;
        });
      }
    }
  } catch (err) {
    console.warn('[Overpass OSM] API fetch failed, falling back to local campus catalog:', err);
  }

  return getCampusLandmarks(normalizedCampus);
}

export function getCampusLandmarks(campusFilter?: string | null): CampusLandmark[] {
  if (!campusFilter || campusFilter.toUpperCase() === 'GLOBAL') return CAMPUS_LANDMARKS;
  const upper = campusFilter.toUpperCase();
  return CAMPUS_LANDMARKS.filter((l) => l.campus.toUpperCase() === upper);
}

export function searchLandmarks(
  query: string,
  campus?: string | null,
  customList?: CampusLandmark[]
): CampusLandmark[] {
  const campusUpper = (campus && campus.toUpperCase() !== 'GLOBAL') ? campus.toUpperCase() : null;
  const base = customList || getCampusLandmarks(campusUpper);
  const scoped = campusUpper ? base.filter((l) => l.campus.toUpperCase() === campusUpper) : base;
  const q = query.toLowerCase().trim();
  if (!q) return scoped;
  return scoped.filter(
    (l) =>
      l.name.toLowerCase().includes(q) ||
      (l.shortCode && l.shortCode.toLowerCase().includes(q)) ||
      l.category.toLowerCase().includes(q) ||
      l.description.toLowerCase().includes(q) ||
      (l.walkingTip && l.walkingTip.toLowerCase().includes(q))
  );
}

export function getOsmEmbedUrl(lat: number, lon: number, zoom: number = 17): string {
  const delta = 0.003;
  const minLon = lon - delta;
  const minLat = lat - delta;
  const maxLon = lon + delta;
  const maxLat = lat + delta;
  return `https://www.openstreetmap.org/export/embed.html?bbox=${minLon}%2C${minLat}%2C${maxLon}%2C${maxLat}&layer=mapnik&marker=${lat}%2C${lon}`;
}

export function getDirectionsUrl(toLat: number, toLon: number, name?: string): string {
  const label = name ? encodeURIComponent(name) : 'Destination';
  return `https://www.google.com/maps/dir/?api=1&destination=${toLat},${toLon}&destination_place_id=${label}`;
}
