import {
  AlumniDirectoryEntry,
  Announcement,
  AppNotification,
  CampusEvent,
  Conversation,
  IncomingConnectionRequest,
  JobListing,
  MarketplaceListing,
  Mentorship,
  MentorProfile,
  Message,
  Post,
  Report,
  Resource,
  StudyGroup,
} from './types';

export const mockPosts: Post[] = [
  {
    id: 'my-post-1',
    authorId: 'me',
    authorName: 'You',
    authorAvatarUrl: 'avatar_male',
    authorRole: 'student',
    authorTrustLevel: 8,
    title: 'Building Open-Source Attendance App for CSC Department 🚀',
    content: 'Just deployed the first beta of our campus attendance & study squad system. Looking for 5 beta testers from 300L CS to test QR check-in!',
    category: 'Tech Hub',
    visibilityScope: 'student',
    scopeVisibility: 'campus',
    institutionCode: 'UI',
    courseTags: 'CSC 301, React Native',
    imageUrl: 'event_tech_hackathon',
    likesCount: 84,
    commentsCount: 19,
    isLikedByMe: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'my-post-2',
    authorId: 'me',
    authorName: 'You',
    authorAvatarUrl: 'avatar_male',
    authorRole: 'student',
    authorTrustLevel: 8,
    title: 'Algorithms Midterm Review Poll 📊',
    content: 'Which chapter do we focus on during Saturday peer study session in Faculty Library?',
    category: 'Academic',
    visibilityScope: 'student',
    scopeVisibility: 'campus',
    institutionCode: 'UI',
    courseTags: 'CSC 301',
    poll: {
      question: 'Which module needs the most practice?',
      options: [
        { id: 'opt-my-1', label: 'Dynamic Programming & Memoization', votes: 56 },
        { id: 'opt-my-2', label: 'Graph Algorithms (Dijkstra/A*)', votes: 41 },
        { id: 'opt-my-3', label: 'Greedy & Divide-and-Conquer', votes: 18 },
      ],
      totalVotes: 115,
      expiresIn: '3 days left',
    },
    likesCount: 62,
    commentsCount: 14,
    isLikedByMe: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: 'post-poll-1',
    authorId: 'student-3',
    authorName: 'Amina Yusuf',
    authorAvatarUrl: null,
    authorRole: 'student',
    authorTrustLevel: 7,
    title: 'CSC 301 Revision Session Timing 📊',
    content: 'Dr. Adeyemi agreed to host an extra exam prep and algorithm review session. Which time slot works best for our department?',
    category: 'Academic',
    visibilityScope: 'student',
    scopeVisibility: 'campus',
    institutionCode: 'UI',
    courseTags: 'CSC 301, Algorithms',
    poll: {
      question: 'Best time for CSC 301 exam prep session?',
      options: [
        { id: 'opt-1', label: 'Thursday 2:00 PM (LT2 Hall)', votes: 42 },
        { id: 'opt-2', label: 'Friday 4:30 PM (Virtual Zoom)', votes: 68 },
        { id: 'opt-3', label: 'Saturday 10:00 AM (Main Hall)', votes: 23 },
      ],
      totalVotes: 133,
      expiresIn: '2 days left',
    },
    likesCount: 54,
    commentsCount: 16,
    isLikedByMe: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: 'post-showcase-1',
    authorId: 'student-4',
    authorName: 'Tunde Bakare',
    authorAvatarUrl: null,
    authorRole: 'student',
    authorTrustLevel: 9,
    title: 'Hackfest 2026: Team Aqua Prototype 🚀',
    content: 'Excited to showcase our smart campus attendance & study squad prototype built during the 48h hackathon! Check out the workshop demo:',
    category: 'Tech Hub',
    visibilityScope: 'global',
    scopeVisibility: 'campus',
    courseTags: 'React Native, Expo, AI',
    imageUrl: 'event_tech_hackathon',
    likesCount: 112,
    commentsCount: 28,
    isLikedByMe: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'post-1',
    authorId: 'staff-1',
    authorName: 'Dean of Students',
    authorAvatarUrl: null,
    authorRole: 'staff',
    authorTrustLevel: 8,
    title: 'Fall Career Fair — Register Your Table',
    content:
      'Employers can now register for booths at this year\u2019s Fall Career Fair. Student RSVPs open next week.',
    category: 'Career',
    visibilityScope: 'global',
    scopeVisibility: 'campus',
    institutionCode: 'FUNAAB',
    likesCount: 42,
    commentsCount: 6,
    isLikedByMe: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    sponsored: true,
  },
  {
    id: 'post-3',
    authorId: 'staff-2',
    authorName: 'UNILAG Student Affairs',
    authorAvatarUrl: null,
    authorRole: 'staff',
    authorTrustLevel: 6,
    title: 'Hostel Allocation Portal Reopens Monday',
    content: 'Returning students can re-apply for hostel space starting Monday 8am. Bring your matric card.',
    category: 'Housing',
    visibilityScope: 'student',
    scopeVisibility: 'campus',
    institutionCode: 'UNILAG',
    likesCount: 58,
    commentsCount: 11,
    isLikedByMe: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
  },
  {
    id: 'post-4',
    authorId: 'staff-3',
    authorName: 'UI Senate Office',
    authorAvatarUrl: null,
    authorRole: 'staff',
    authorTrustLevel: 6,
    title: 'Convocation Rehearsal Schedule Released',
    content: 'Departmental rehearsal slots for this year\u2019s convocation are now posted on the notice board.',
    category: 'Academic',
    visibilityScope: 'student',
    scopeVisibility: 'campus',
    institutionCode: 'UI',
    likesCount: 33,
    commentsCount: 4,
    isLikedByMe: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
  },
  {
    id: 'post-2',
    authorId: 'alumni-9',
    authorName: 'Priya N. \u201918',
    authorAvatarUrl: null,
    authorRole: 'alumni',
    authorTrustLevel: 12,
    title: 'Hiring interns at Lightbeam Robotics',
    content: 'We\u2019re bringing on 3 summer interns from the CS and ME departments — happy to chat.',
    category: 'Opportunities',
    visibilityScope: 'global',
    scopeVisibility: 'global',
    imageUrl: null,
    likesCount: 87,
    commentsCount: 19,
    isLikedByMe: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
];

export const mockEvents: CampusEvent[] = [
  {
    id: 'event-1',
    organizerId: 'staff-2',
    title: 'Alumni Networking Mixer',
    description: 'An evening mixer for alumni and graduating seniors in the Bay Area.',
    category: 'alumni',
    location: 'Innovation Hall, Rm 220',
    visibilityScope: 'alumni',
    startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3).toISOString(),
    endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 3 + 1000 * 60 * 90).toISOString(),
    capacity: 120,
    rsvpCount: 78,
    isRsvpd: false,
  },
  {
    id: 'event-2',
    organizerId: 'staff-3',
    title: 'Resume Workshop with Career Services',
    description: 'Bring a draft resume for live feedback from career coaches.',
    category: 'workshop',
    location: 'Online — link shared after RSVP',
    visibilityScope: 'student',
    startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(),
    endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5 + 1000 * 60 * 60).toISOString(),
    capacity: null,
    rsvpCount: 34,
    isRsvpd: true,
    sponsored: true,
  },
  {
    id: 'event-3',
    organizerId: 'staff-4',
    title: 'Intro to Machine Learning Seminar',
    description: 'A guest lecture on modern ML techniques, open to all CS-adjacent majors.',
    category: 'seminar',
    location: 'Turing Hall, Auditorium B',
    visibilityScope: 'student',
    startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2).toISOString(),
    endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 2 + 1000 * 60 * 75).toISOString(),
    capacity: 200,
    rsvpCount: 156,
    isRsvpd: false,
  },
  {
    id: 'event-4',
    organizerId: 'staff-5',
    title: 'Midterm Study Jam',
    description: 'Group study session with TAs on hand for Calc II and Intro Physics.',
    category: 'academic',
    location: 'Library, 3rd Floor Commons',
    visibilityScope: 'student',
    startAt: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 + 1000 * 60 * 120).toISOString(),
    capacity: 60,
    rsvpCount: 60,
    isRsvpd: false,
  },
  {
    id: 'event-5',
    organizerId: 'alumni-14',
    title: 'Founders & Alumni Fireside Chat',
    description: 'Three alumni founders talk about their first two years post-grad.',
    category: 'career',
    location: 'Innovation Hall, Rm 105',
    visibilityScope: 'alumni',
    startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
    endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10 + 1000 * 60 * 90).toISOString(),
    capacity: 80,
    rsvpCount: 22,
    isRsvpd: false,
  },
  {
    id: 'event-6',
    organizerId: 'staff-2',
    title: 'Homecoming Weekend Kickoff',
    description: 'Campus-wide kickoff celebration for Homecoming Weekend — food trucks and live music.',
    category: 'alumni',
    location: 'Main Quad',
    visibilityScope: 'global',
    startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 20).toISOString(),
    endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 20 + 1000 * 60 * 180).toISOString(),
    capacity: null,
    rsvpCount: 410,
    isRsvpd: false,
  },
  {
    id: 'event-7',
    organizerId: 'staff-2',
    organizerName: 'Emmanuel Inem',
    title: 'CSC 301 Study Blitz',
    description:
      'Comprehensive review of past questions and coding exam prep. Free pizza and coffee will be provided by senior students.',
    category: 'academic',
    location: 'CS Department Hall 2',
    visibilityScope: 'student',
    startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4).toISOString(),
    endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 4 + 1000 * 60 * 120).toISOString(),
    capacity: null,
    rsvpCount: 41,
    isRsvpd: true,
    approvalStatus: 'approved',
    attendeeNames: ['Adebayo Salami', 'Chisom Obi', 'Ngozi Coker'],
  },
  {
    id: 'event-8',
    organizerId: 'staff-3',
    organizerName: 'Lioris Tech Council',
    title: 'UNILAG Tech Odyssey Hackathon',
    description:
      'Join programmers and engineers building solutions for Nigerian campus challenges. Cash prizes & direct incubation pathways.',
    category: 'career',
    location: 'UNILAG CITS Tech Hub',
    visibilityScope: 'global',
    startAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 12).toISOString(),
    endAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 13).toISOString(),
    capacity: null,
    rsvpCount: 89,
    isRsvpd: false,
    approvalStatus: 'approved',
  },
];

export const mockDirectory: AlumniDirectoryEntry[] = [
  {
    id: 'alumni-9',
    fullName: 'Priya Nair',
    graduationYear: 2018,
    bio: 'Robotics engineer, ex-Boston Dynamics. Happy to talk grad school or industry.',
    industry: 'Robotics',
    company: 'Lightbeam Robotics',
    avatarUrl: null,
    connectionStatus: 'none',
  },
  {
    id: 'alumni-14',
    fullName: 'Marcus Webb',
    graduationYear: 2015,
    bio: 'Product lead in fintech. Mentors 2 students per semester.',
    industry: 'Fintech',
    company: 'Northline',
    avatarUrl: null,
    connectionStatus: 'pending',
  },
  {
    id: 'alumni-21',
    fullName: 'Sofia Alvarez',
    graduationYear: 2020,
    bio: 'Backend engineer working on payments infrastructure. Always happy to talk system design.',
    industry: 'Fintech',
    company: 'Meridian Pay',
    avatarUrl: null,
    connectionStatus: 'none',
  },
  {
    id: 'alumni-27',
    fullName: 'Daniel Osei',
    graduationYear: 2012,
    bio: 'Runs a small robotics consultancy. Looking to mentor students interested in hardware.',
    industry: 'Robotics',
    company: 'Osei Automation',
    avatarUrl: null,
    connectionStatus: 'none',
  },
  {
    id: 'alumni-33',
    fullName: 'Grace Lin',
    graduationYear: 2019,
    bio: 'UX researcher at a healthcare startup. Loves talking about design careers.',
    industry: 'Healthcare',
    company: 'Vitalis Health',
    avatarUrl: null,
    connectionStatus: 'accepted',
  },
  {
    id: 'alumni-40',
    fullName: 'Ben Carter',
    graduationYear: 2016,
    bio: 'Data scientist in climate tech. Previously worked in academic research.',
    industry: 'Climate Tech',
    company: 'Verdant Analytics',
    avatarUrl: null,
    connectionStatus: 'none',
  },
];

export const mockMentorProfiles: MentorProfile[] = [
  {
    id: 'alumni-14',
    fullName: 'Marcus Webb',
    avatarUrl: null,
    department: 'Computer Science',
    expertiseTags: ['Software', 'Resume Prep'],
    bio: 'Product lead in fintech. Mentors 2 students per semester on career and interview prep.',
    company: 'Northline',
    availableSlots: 2,
  },
  {
    id: 'alumni-9',
    fullName: 'Priya Nair',
    avatarUrl: null,
    department: 'Mechanical Engineering',
    expertiseTags: ['Software', 'Research'],
    bio: 'Robotics engineer, ex-Boston Dynamics. Happy to talk grad school or industry.',
    company: 'Lightbeam Robotics',
    availableSlots: 1,
  },
  {
    id: 'alumni-33',
    fullName: 'Grace Lin',
    avatarUrl: null,
    department: 'Design',
    expertiseTags: ['Design', 'Resume Prep'],
    bio: 'UX researcher at a healthcare startup. Loves talking about design careers and portfolios.',
    company: 'Vitalis Health',
    availableSlots: 3,
  },
  {
    id: 'alumni-40',
    fullName: 'Ben Carter',
    avatarUrl: null,
    department: 'Data Science',
    expertiseTags: ['Software', 'Finance'],
    bio: 'Data scientist in climate tech. Previously worked in academic research.',
    company: 'Verdant Analytics',
    availableSlots: 1,
  },
];

export const mockIncomingConnectionRequests: IncomingConnectionRequest[] = [
  {
    id: 'incoming-1',
    requesterId: 'alumni-21',
    requesterName: 'Sofia Alvarez',
    requesterAvatarUrl: null,
    requesterHeadline: 'Backend engineer at Meridian Pay \u00b7 Class of 2020',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 'incoming-2',
    requesterId: 'alumni-40',
    requesterName: 'Ben Carter',
    requesterAvatarUrl: null,
    requesterHeadline: 'Data scientist at Verdant Analytics \u00b7 Class of 2016',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participantId: 'alumni-14',
    participantName: 'Marcus Webb',
    participantAvatarUrl: null,
    isOnline: true,
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    lastMessagePreview: 'Sounds good — let\u2019s find time next week.',
    unreadCount: 1,
  },
];

export const mockMessages: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1',
      conversationId: 'conv-1',
      senderId: 'me',
      content: 'Hi Marcus! Would love to hear about your path into fintech PM roles.',
      messageType: 'text',
      status: 'read',
      sentAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    },
    {
      id: 'msg-2',
      conversationId: 'conv-1',
      senderId: 'alumni-14',
      content: 'Happy to! Are you free for a quick call sometime next week?',
      messageType: 'text',
      status: 'read',
      sentAt: new Date(Date.now() - 1000 * 60 * 41).toISOString(),
    },
    {
      id: 'msg-3',
      conversationId: 'conv-1',
      senderId: 'alumni-14',
      content: 'Sounds good — let\u2019s find time next week.',
      messageType: 'text',
      status: 'delivered',
      sentAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    },
  ],
};

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    type: 'event',
    title: 'Event reminder',
    body: 'Alumni Networking Mixer starts in 3 days.',
    channel: 'in_app',
    deliveryStatus: 'delivered',
    createdAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    deepLinkPath: '/(alumni)/events/event-1',
  },
  {
    id: 'notif-2',
    type: 'message',
    title: 'New message from Marcus Webb',
    body: 'Sounds good — let\u2019s find time next week.',
    channel: 'push',
    deliveryStatus: 'delivered',
    createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    deepLinkPath: '/(alumni)/messages/conv-1',
  },
];

export const mockMentorships: Mentorship[] = [
  {
    id: 'ment-1',
    studentId: 'me',
    mentorId: 'alumni-14',
    mentorName: 'Marcus Webb',
    status: 'active',
    focusArea: 'Career',
  },
  {
    id: 'ment-2',
    studentId: 'student-8',
    mentorId: 'me',
    mentorName: 'You',
    status: 'pending',
    focusArea: 'Academics',
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    authorId: 'staff-1',
    authorName: 'Office of the Dean',
    title: 'Midterm Advising Week',
    content: 'Advising slots open Monday. Book early — popular slots fill fast.',
    audienceScope: 'student',
    priority: 'normal',
    publishedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
];

export const mockReports: Report[] = [
  {
    id: 'report-1',
    reporterId: 'student-3',
    targetType: 'post',
    targetId: 'post-2',
    reason: 'Suspected spam / off-topic solicitation',
    status: 'open',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    institutionCode: 'FUNAAB',
  },
  {
    id: 'report-2',
    reporterId: 'student-11',
    targetType: 'event',
    targetId: 'event-7',
    reason: 'Duplicate listing of an existing study session',
    status: 'open',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    institutionCode: 'UNILAG',
  },
  {
    id: 'report-3',
    reporterId: 'student-22',
    targetType: 'message',
    targetId: 'msg-1',
    reason: 'Unsolicited off-platform payment request',
    status: 'under_review',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
    institutionCode: 'UI',
  },
];

export const mockMarketplaceListings: MarketplaceListing[] = [
  {
    id: 'mkt-1',
    title: 'MacBook Air M1 (2020) — Great condition',
    description: 'Barely used, comes with charger and a sleeve. Great for CS coursework.',
    price: '\u20a6320,000',
    condition: 'Like New',
    category: 'Electronics',
    imageUrl: null,
    sellerName: 'Tunde A.',
    sellerAvatarUrl: null,
    sellerId: 'student-11',
    sellerTrustLevel: 6,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: 'mkt-2',
    title: 'Calculus: Early Transcendentals (Thomas)',
    description: 'Used for MATH201. A few highlighter marks, otherwise in good shape.',
    price: '\u20a68,500',
    condition: 'Fair',
    category: 'Books/Academic',
    imageUrl: null,
    sellerName: 'Chioma N.',
    sellerAvatarUrl: null,
    sellerId: 'student-22',
    sellerTrustLevel: 2,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
  },
  {
    id: 'mkt-3',
    title: 'Study desk + chair set',
    description: 'Moving out of the hostel, selling my desk and chair together. Pickup only.',
    price: '\u20a615,000',
    condition: 'Like New',
    category: 'Furniture/Room Accessories',
    imageUrl: null,
    sellerName: 'Adebayo O.',
    sellerAvatarUrl: null,
    sellerId: 'student-33',
    sellerTrustLevel: 4,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
  },
  {
    id: 'mkt-4',
    title: 'Sony WH-1000XM4 headphones',
    description: 'Excellent noise cancelling, great for studying in the library. Includes case.',
    price: '\u20a695,000',
    condition: 'Like New',
    category: 'Electronics',
    imageUrl: null,
    sellerName: 'Priya N.',
    sellerAvatarUrl: null,
    sellerId: 'alumni-9',
    sellerTrustLevel: 11,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
];

export const mockJobListings: JobListing[] = [
  {
    id: 'job-1',
    title: 'Summer Software Engineering Intern',
    company: 'Lightbeam Robotics',
    location: 'Remote',
    type: 'Internship',
    remote: true,
    applyUrl: 'https://example.com/apply/lightbeam',
    postedByName: 'Priya Nair',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: 'job-2',
    title: 'Junior Product Analyst',
    company: 'Northline',
    location: 'Lagos, Nigeria',
    type: 'Full-time',
    remote: false,
    applyUrl: 'https://example.com/apply/northline',
    postedByName: 'Marcus Webb',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 40).toISOString(),
  },
  {
    id: 'job-3',
    title: 'Part-time Campus Ambassador',
    company: 'Verdant Analytics',
    location: 'On campus',
    type: 'Part-time',
    remote: false,
    applyUrl: 'https://example.com/apply/verdant',
    postedByName: 'Ben Carter',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 60).toISOString(),
  },
];

export const mockStudyGroups: StudyGroup[] = [
  {
    id: 'sg-1',
    name: 'CSC 305 Study Circle',
    courseCode: 'CSC305',
    description: 'Weekly problem sets and past-question review for Algorithms.',
    memberCount: 18,
    isPublic: true,
    isJoined: true,
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'sg-2',
    name: 'MATH201 Calc II Crew',
    courseCode: 'MATH201',
    description: 'Group working through Thomas\u2019 Calculus together before exams.',
    memberCount: 24,
    isPublic: true,
    isJoined: false,
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: 'sg-3',
    name: 'Robotics Club Inner Circle',
    courseCode: 'ENG410',
    description: 'Private group for the robotics competition team.',
    memberCount: 9,
    isPublic: false,
    isJoined: true,
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
];

export const mockResources: Resource[] = [
  {
    id: 'res-1',
    title: 'CSC305 Algorithms — Midterm Past Questions (2023-2024)',
    description: 'Compiled past questions with worked solutions for the algorithms midterm.',
    category: 'Past Questions',
    department: 'Computer Science',
    courseCode: 'CSC305',
    fileSize: '2.1 MB',
    authorName: 'Tunde A.',
    likesCount: 64,
    downloadsCount: 312,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: 'res-2',
    title: 'MATH201 Lecture Notes — Weeks 1-6',
    description: 'Typed lecture notes covering limits, derivatives, and integration basics.',
    category: 'Notes',
    department: 'Mathematics',
    courseCode: 'MATH201',
    fileSize: '850 KB',
    authorName: 'Chioma N.',
    likesCount: 41,
    downloadsCount: 198,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 8).toISOString(),
  },
  {
    id: 'res-3',
    title: 'Final Year Project — Smart Irrigation System (Report)',
    description: 'Full project report and poster for a final-year embedded systems project.',
    category: 'Projects',
    department: 'Electrical Engineering',
    courseCode: 'ENG499',
    fileSize: '5.4 MB',
    authorName: 'Adebayo O.',
    likesCount: 22,
    downloadsCount: 87,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
  },
];
